name: Daily Selenium Submit

on:
  schedule:
    # 广东时间 15:00 => UTC 07:00
    - cron: "0 07 * * *"
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub \
            | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] \
            http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run Selenium submit
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD:  ${{ secrets.PASSWORD }}
          MAX_STEP:  ${{ secrets.MAX_STEP }}
          MIN_STEP:  ${{ secrets.MIN_STEP }}
        run: python ibushu.py

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: after-screenshot
          path: after.png
