name: Run Zepp Script

on:
  schedule:
    # 每天北京时间 15 点运行（UTC 时间减 8 小时）
    - cron: '0 7 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          ZEPP_ACCOUNT: ${{ secrets.ZEPP_ACCOUNT }}
          ZEPP_PASSWORD: ${{ secrets.ZEPP_PASSWORD }}
          MIN_STEP: ${{ secrets.MIN_STEP }}
          MAX_STEP: ${{ secrets.MAX_STEP }}
        run: python submit_step.py
